// env.ts
import { z } from "zod";

// Define your environment variable schema
const schema = z.object({
  EXPO_PUBLIC_SUPABASE_URL: z.string().url(),
  EXPO_PRIVATE_SUPABASE_API_KEY: z.string().min(1),
  EXPO_PUBLIC_SUPABASE_API_KEY: z.string().min(1),
  EXPO_PUBLIC_STRIPEPUBLISHABLE_KEY: z.string().min(1),
  EXPO_PUBLIC_STRIPESECRET_KEY: z.string().min(1),
  EXPO_PUBLIC_BACKEND_URL: z.string().min(1),
  EXPO_PUBLIC_CLOUDINARY_UPLOAD_URL: z.string().min(1),
  EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET: z.string().min(1),
  EXPO_PUBLIC_CLOUDINARY_API_Key: z.string().min(1),
  EXPO_PUBLIC_CLOUDINARY_API_SECRET: z.string(),
});

// Validate and parse environment variables
const Env = schema.parse({
  EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
  EXPO_PRIVATE_SUPABASE_API_KEY: process.env.EXPO_PRIVATE_SUPABASE_API_KEY,
  EXPO_PUBLIC_SUPABASE_API_KEY: process.env.EXPO_PUBLIC_SUPABASE_API_KEY,
  EXPO_PUBLIC_STRIPEPUBLISHABLE_KEY:
    process.env.EXPO_PUBLIC_STRIPEPUBLISHABLE_KEY,
  EXPO_PUBLIC_STRIPESECRET_KEY: process.env.EXPO_PUBLIC_STRIPESECRET_KEY,
  EXPO_PUBLIC_BACKEND_URL: process.env.EXPO_PUBLIC_BACKEND_URL,
  EXPO_PUBLIC_CLOUDINARY_UPLOAD_URL: process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_URL,
  EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET: process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
  EXPO_PUBLIC_CLOUDINARY_API_Key: process.env.EXPO_PUBLIC_CLOUDINARY_API_Key,
  EXPO_PUBLIC_CLOUDINARY_API_SECRET: process.env.EXPO_PUBLIC_CLOUDINARY_API_SECRET,
});

console.log(Env);

// Export the validated environment variables
export { Env };
